export enum DeliveryStatus {
  QUEUED =  1,
  RINGING =  2,
  IN_PROGRESS =  3,
  WAITING_TO_RETRY =  4,
  FAILED_NO_ANSWER =  5,
  FINISHED_COMPLETE =  6,
  FINISHED_INCOMPLETE =  7,
  // FAILED_NO_CREDIT =  8,
  FAILED_NETWORK =  9,
  FAILED_CANCELLED =  10,
  SENT =  11,
  FINISHED_VOICEMAIL =  12,
  FAILED_VOICEMAIL =  13,
  FAILED_ERROR =  14,
}

export default DeliveryStatus
