name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ESLint
          # You may pin to the exact commit or the version.
          # uses: getsentry/action-eslint-fix@27453ba6ed4bbf6c4d2425febef0121375caea75
        uses: getsentry/action-eslint-fix@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
